- name: MySQL Server
  hosts: mysql
  become: yes

  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: Start MySQL Service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
    
  - name: set the default root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

